version: '2.1'
services:
  postgresql:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=apm
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=apm_demo_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  ruby-app:
    build: ../ruby-app
    image: rubyapp
    env_file:
      - "../ruby-app/.env.dev"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - ../ruby-app:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRESQL_HOST: postgresql
    depends_on:
      postgresql:
        condition: service_healthy
volumes:
  bundle:
  db-data:

