auditbeat.modules:

  - module: auditd
    resolve_ids: true
    failure_mode: silent
    backlog_limit: 8196
    rate_limit: 0
    include_raw_message: false
    include_warnings: false
    audit_rules: |
      ## Define audit rules here.
      ## Create file watches (-w) or syscall audits (-a action,filter).
      ## * action can be either always or never.
      ## * filter specifies which kernel rule-matching filter is applied to the event,
      ##   which can be one of the following: task, exit, user, and exclude.
      ## Several system calls can be grouped into one rule, each specified after the -S option.
      ## For a full list of system calls see /usr/include/x86_64-linux-gnu/asm/unistd_64.h.
      ## Add a keyword (-k) to the log event.
      # Log read access to passwd from selected users (1001=developers)
      -a always,exit -F path=/etc/pam.conf -F perm=r -F uid=1001 -k developers-pam-read
      # Detect when an admin may be abusing power by looking in a user's home directory
      -a always,exit -F dir=/home -F uid=0 -F auid>=1000 -F auid!=4294967295 -C auid!=obj_uid -k power-abuse
      # Log all elevation of privileges
      -a always,exit -S setuid -F a0=0 -F exe=/usr/bin/su -k elevated-privs
      -a always,exit -S setresuid -F a0=0 -F exe=/usr/bin/sudo -k elevated-privs
      -a always,exit -S execve -C uid!=euid -F euid=0 -k elevated-privs
      # Log processes that call the (outgoing) connect system call
      #-a always,exit -S connect -k connect-out
      # Log processes opening a socket
      -a always,exit -S socket -k open-socket
      # Log all executed processes
      #-a always,exit -S execve -k process-execution
  - module: system
    datasets:
      - host # General host information, e.g. uptime, IPs
      - user # User information
    period: 1m
    user.detect_password_changes: true


  - module: system
    datasets:
      - process # Started and stopped processes
      - socket  # Opened and closed sockets
    period: 1s


  - module: file_integrity
    paths:
      - /opt/
    scan_at_start: true
    scan_rate_per_sec: 50 MiB
    file.max_file_size: 100 MiB
    file.hash_types: [sha1]


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "gcp"]


processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~


xpack.monitoring.enabled: true

cloud.id: "${EC_ID}"
cloud.auth: "${EC_AUTH}"

output.elasticsearch:
  hosts: []


setup:
  kibana:
  dashboards.enabled: true