filebeat.inputs:

  # Collect the JSON log files from Lograge
  - type: log
    paths:
      - /webapp/log/lograge_*.log
    fields_under_root: true
    fields:
      application: ruby
# TODO set true if Lograge can change json key name
#    json.keys_under_root: true
    json.add_error_key: true


filebeat.modules:
  - module: auditd
  - module: system
{% if inventory_hostname_short == 'frontend' %}
  - module: nginx
{% endif %}
{% if inventory_hostname_short == 'backend' %}
  - module: postgresql
{% endif %}


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "gcp"]


processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
{% if inventory_hostname_short == 'frontend' %}
  - convert:
      mode: "rename"
      fields:
        - {from: "json.error", to: "json.error_msg", type: "string"}
{% endif %}

xpack.monitoring.enabled: true

cloud.id: "${EC_ID}"
cloud.auth: "${EC_AUTH}"

output.elasticsearch:
  hosts: ["localhost"]


setup:
  kibana:
  dashboards.enabled: true