metricbeat.modules:

  - module: system
    metricsets:
      - cpu
      - load
      - core
      - diskio
      - filesystem
      - fsstat
      - memory
      - network
      - process
      - process_summary
      - socket
    enabled: true
    period: 10s
    processes: ['.*']
    cgroups: true
    process.include_top_n:
      enabled: true
      by_cpu: 20
      by_memory: 20

{% if inventory_hostname_short == 'frontend' %}
  - module: nginx
    metricsets: ["stubstatus"]
    enabled: true
    period: 10s
    hosts: ["https://{{ inventory_hostname }}"]
{% endif %}

{% if inventory_hostname_short == 'backend' %}
  - module: postgresql
    hosts: ["postgres://{{ postgresql_user }}:{{ postgresql_password }}@{{ postgresql_server }}:5432/{{ postgresql_database }}"]
{% endif %}

name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "gcp"]


processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~


xpack.monitoring.enabled: true

cloud.id: "${EC_ID}"
cloud.auth: "${EC_AUTH}"

output.elasticsearch:
  hosts: ["localhost"]


setup:
  kibana:
  dashboards.enabled: true