filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /mnt/ruby-app-log/lograge_*.log
  fields_under_root: true
  fields:
    application: java
    layer: ruby
  json.keys_under_root: true
  json.add_error_key: true

# Module: mysql
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.1/filebeat-module-mysql.html

filebeat.modules:
- module: system
- module: postgresql
  log:
    enabled: true
    var.paths: ["/mnt/postgresql-log/*"]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

cloud.id: '${ELASTIC_CLOUD_ID:}'
cloud.auth: '${ELASTIC_CLOUD_AUTH:}'

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOSTS:}']
  protocol: "https"

xpack.monitoring.enabled: true

#setup.kibana:
#setup.dashboards.enabled: true
#setup.dashboards.retry.enabled: true
#setup.dashboards.retry.interval: 5s
